language: node_js
node_js:
  - 14
services:
  - postgresql
addons:
  postgresql: '9.6'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_script:
  - psql -c 'create database "note-ary-test";' -U postgres
script:
  - npm test
  - npm run build-client
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: note-ary # see README
  api_key:
    secure: nxOIeDY6i9nLaY38SRcR8xkEMHzOqIVKZMAJ3HDGIj+kP7jfWJZrXcT5w+G2Grgcqrw3KAeE4BzLcyPHPUknGoAxFrRLgA3a8L/G9HCU/l3xtUvoaTjWppNjlJagHo/ZCmw4GLjjDKlsvxJxwZeWl3RGK8uiOXtpwGjXCzIyBn7uTq/uzyPn3tDLCYK60i5CnvfPB1FJu1ysYDb8At0q16464RCeg00cG525cPQCZ+eB1hy5nwZZ9Z6Ti5Qzg75oliLzrtPmpoLQBA4VTOHz7TnkHJVih3pBQR41gmQhReorAN7St6L3FF1fhr/Ok05BIbsKPjAwyP9NJfh/1LodF/7cXWvR1gVXM64GQzFXBLfn5ITP4NZEkTH9w4Uvv9Tr11nTMVZ/vMBejPBhyWDu22R848suQ7YivLkwzi3/PmTCE0GjVD9aPf25/0ojwgLOPSmdWPfpDK3INOR1d2rNhnWFIATyd0mwnItxugEB5GP/LTQQcv++oaCc0qrKKi4KgJ18rfJY9uwpghNQsK3+J9p0W1N3LVNxkDuSolSBFy34LrJk4btaQoGDJBfJnGVQo3ZYfY9ofVffefZ20YAQHMcZbTIpFzvGxPewhdK3Y6pmUpp6NgaSk6qBOLxc6TgU9GLhD6jWlvFyrFIfn85OCgE328Xdpd00uaC8PLrULsE=
